# Generated by Django 4.0.2 on 2022-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='do',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
